### ISSUE TITLE
Why does the app require the Bluetooth module

### ISSUE THREAD

**Issue by cosminpolifronie** [unitbvcv/image_processing_platform#13]
The app requires the Bluetooth module in order to start. This module is only compatible with Windows 10 in PyQt 5.11.3.

Error in Windows 8.1:

> This Windows version (6.3.9600) does not support the required bluetooth API.

**Comment by cosminpolifronie** [comment]
Message received when trying to uninstall PyQt5 while the app is running:

> C:\Windows\system32>pip uninstall pyqt5
Uninstalling PyQt5-5.11.3:
  Would remove:
    c:\users\cosmin\appdata\local\programs\python\python37\lib\site-packages\pyqt5-5.11.3.dist-info\*
    c:\users\cosmin\appdata\local\programs\python\python37\lib\site-packages\pyqt5\*
    c:\users\cosmin\appdata\local\programs\python\python37\scripts\pylupdate5.exe
    c:\users\cosmin\appdata\local\programs\python\python37\scripts\pyrcc5.exe
    c:\users\cosmin\appdata\local\programs\python\python37\scripts\pyuic5.exe
  Would not remove (might be manually added):
    c:\users\cosmin\appdata\local\programs\python\python37\lib\site-packages\pyqt5\sip.pyd
Proceed (y/n)? y
  Successfully uninstalled PyQt5-5.11.3
Exception:
Traceback (most recent call last):
  File "c:\users\cosmin\appdata\local\programs\python\python37\lib\shutil.py", line 395, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\Cosmin\\AppData\\Local\\Temp\\pip-uninstall-dw4mk24z\\users\\cosmin\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\pyqt5\\qt\\bin\\qt5bluetooth.dll'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\cosmin\appdata\local\programs\python\python37\lib\site-packages\pip\_internal\cli\base_command.py", line 143, in main
    status = self.run(options, args)
  File "c:\users\cosmin\appdata\local\programs\python\python37\lib\site-packages\pip\_internal\commands\uninstall.py", line 78, in run
    uninstall_pathset.commit()
  File "c:\users\cosmin\appdata\local\programs\python\python37\lib\site-packages\pip\_internal\req\req_uninstall.py", line 275, in commit
    self.save_dir.cleanup()
  File "c:\users\cosmin\appdata\local\programs\python\python37\lib\site-packages\pip\_internal\utils\temp_dir.py", line 81, in cleanup
    rmtree(self.path)
  File "c:\users\cosmin\appdata\local\programs\python\python37\lib\site-packages\pip\_vendor\retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "c:\users\cosmin\appdata\local\programs\python\python37\lib\site-packages\pip\_vendor\retrying.py", line 212, in call
    raise attempt.get()
  File "c:\users\cosmin\appdata\local\programs\python\python37\lib\site-packages\pip\_vendor\retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "c:\users\cosmin\appdata\local\programs\python\python37\lib\site-packages\pip\_vendor\six.py", line 693, in reraise
    raise value
  File "c:\users\cosmin\appdata\local\programs\python\python37\lib\site-packages\pip\_vendor\retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "c:\users\cosmin\appdata\local\programs\python\python37\lib\site-packages\pip\_internal\utils\misc.py", line 111, in rmtree
    onerror=rmtree_errorhandler)
  File "c:\users\cosmin\appdata\local\programs\python\python37\lib\shutil.py", line 513, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "c:\users\cosmin\appdata\local\programs\python\python37\lib\shutil.py", line 392, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "c:\users\cosmin\appdata\local\programs\python\python37\lib\shutil.py", line 392, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "c:\users\cosmin\appdata\local\programs\python\python37\lib\shutil.py", line 392, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  [Previous line repeated 9 more times]
  File "c:\users\cosmin\appdata\local\programs\python\python37\lib\shutil.py", line 397, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "c:\users\cosmin\appdata\local\programs\python\python37\lib\site-packages\pip\_internal\utils\misc.py", line 123, in rmtree_errorhandler
    func(path)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\Cosmin\\AppData\\Local\\Temp\\pip-uninstall-dw4mk24z\\users\\cosmin\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\pyqt5\\qt\\bin\\qt5bluetooth.dll'

**Comment by cosminpolifronie** [comment]
I've found that importing PyQt5.Qt implicitly loads the Bluetooth dll. I think I've found a fix. Testing.

**Comment by cosminpolifronie** [comment]
This showed up again. Debugging.

**Comment by cosminpolifronie** [comment]
False alarm, the user was using an old version of the framework.
